### ISSUE TITLE
How to whitelist characters or ignore errors?

### ISSUE THREAD

**Issue by TheSecurityDev** [davidreis97/Crashacters#14]
Is there any way I can disable the error for a certain line of code, or at least disable the extension for certain characters?

**Comment by davidreis97** [comment]
Hi, you can choose which characters are allowed on the settings of the extension in VSCode, like so:

![image](https://user-images.githubusercontent.com/15610011/185492873-02776669-9da0-4556-a351-b9042ce90d54.png)

If you want to allow a certain character then remove it from the "Character Blacklist".

**Comment by TheSecurityDev** [comment]
I guess that works. I'm trying to exclude some emojis, and it would be nice to just type them into a whitelist or something instead of having to figure out the decimal version of the character code for each one. It would also be nice if you could have overrides for certain files or disable for certain lines.

**Comment by TheSecurityDev** [comment]
I actually figured out I can HTML encode the emoji for my React project and include it that way without errors.
